name: SimpMusic
options:
  bundleIdPrefix: com.maxrave.simpmusic
  deploymentTarget:
    iOS: '16.0'
settings:
  base:
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: ''
targets:
  SimpMusic:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - path: SimpMusicApp.swift
      - path: Assets.xcassets
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: SimpMusic
        CFBundleShortVersionString: '2.1.2'
        CFBundleVersion: '60'
        UILaunchScreen: {}
        CADisableMinimumFrameDurationOnPhone: true
        UIBackgroundModes:
          - audio
        UIApplicationSupportsIndirectInputEvents: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - framework: ../composeApp/build/bin/iosArm64/debugFramework/ComposeApp.framework
        embed: false
    settings:
      base:
        MARKETING_VERSION: '2.1.2'
        CURRENT_PROJECT_VERSION: '60'
        PRODUCT_BUNDLE_IDENTIFIER: com.maxrave.simpmusic.ios
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: '1,2'
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        FRAMEWORK_SEARCH_PATHS: '$(inherited) $(SRCROOT)/../composeApp/build/bin/iosArm64/debugFramework'
